name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Client Docker image
      run: docker build . --file client/Dockerfile --tag $(date +%s)
    - name: Build the nginx Docker image
      run: docker build . --file nginx/Dockerfile --tag $(date +%s)
    - name: Build the worker Docker image
      run: docker build . --file worker/Dockerfile --tag $(date +%s)
